import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function seedPermissions() {
  const permissions = [
    {
      resource: 'orders',
      action: 'view',
      scope: 'own',
      name: 'orders.view.own',
      description: 'Xem đơn hàng của chính mình',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'view',
      scope: 'branch',
      name: 'orders.view.branch',
      description: 'Xem đơn hàng trong chi nhánh',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'view',
      scope: 'all',
      name: 'orders.view.all',
      description: 'Xem tất cả đơn hàng',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'create',
      scope: 'own',
      name: 'orders.create',
      description: 'Tạo đơn hàng',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'update',
      scope: 'own',
      name: 'orders.update.own',
      description: 'Sửa đơn hàng của chính mình',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'update',
      scope: 'branch',
      name: 'orders.update.branch',
      description: 'Sửa đơn hàng trong chi nhánh',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'update',
      scope: 'all',
      name: 'orders.update.all',
      description: 'Sửa tất cả đơn hàng',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'delete',
      scope: 'own',
      name: 'orders.delete.own',
      description: 'Xóa đơn hàng của chính mình',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'delete',
      scope: 'all',
      name: 'orders.delete.all',
      description: 'Xóa tất cả đơn hàng',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'cancel',
      scope: 'own',
      name: 'orders.cancel.own',
      description: 'Hủy đơn hàng của chính mình',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'cancel',
      scope: 'all',
      name: 'orders.cancel.all',
      description: 'Hủy tất cả đơn hàng',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'export',
      scope: 'own',
      name: 'orders.export.own',
      description: 'Xuất dữ liệu đơn hàng của mình',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'export',
      scope: 'all',
      name: 'orders.export.all',
      description: 'Xuất tất cả dữ liệu đơn hàng',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'print',
      scope: 'own',
      name: 'orders.print',
      description: 'In đơn hàng',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'view',
      scope: 'own',
      field: 'discount',
      name: 'orders.view.discount',
      description: 'Xem giảm giá',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'edit',
      scope: 'own',
      field: 'discount',
      name: 'orders.edit.discount',
      description: 'Sửa giảm giá',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'view',
      scope: 'own',
      field: 'cost',
      name: 'orders.view.cost',
      description: 'Xem giá vốn',
      category: 'orders',
    },
    {
      resource: 'orders',
      action: 'view',
      scope: 'own',
      field: 'profit',
      name: 'orders.view.profit',
      description: 'Xem lợi nhuận',
      category: 'orders',
    },
    {
      resource: 'invoices',
      action: 'view',
      scope: 'own',
      name: 'invoices.view.own',
      description: 'Xem hóa đơn của chính mình',
      category: 'invoices',
    },
    {
      resource: 'invoices',
      action: 'view',
      scope: 'branch',
      name: 'invoices.view.branch',
      description: 'Xem hóa đơn trong chi nhánh',
      category: 'invoices',
    },
    {
      resource: 'invoices',
      action: 'view',
      scope: 'all',
      name: 'invoices.view.all',
      description: 'Xem tất cả hóa đơn',
      category: 'invoices',
    },
    {
      resource: 'invoices',
      action: 'create',
      scope: 'own',
      name: 'invoices.create',
      description: 'Tạo hóa đơn',
      category: 'invoices',
    },
    {
      resource: 'invoices',
      action: 'update',
      scope: 'own',
      name: 'invoices.update.own',
      description: 'Sửa hóa đơn của chính mình',
      category: 'invoices',
    },
    {
      resource: 'invoices',
      action: 'update',
      scope: 'all',
      name: 'invoices.update.all',
      description: 'Sửa tất cả hóa đơn',
      category: 'invoices',
    },
    {
      resource: 'invoices',
      action: 'delete',
      scope: 'own',
      name: 'invoices.delete.own',
      description: 'Xóa hóa đơn của chính mình',
      category: 'invoices',
    },
    {
      resource: 'invoices',
      action: 'delete',
      scope: 'all',
      name: 'invoices.delete.all',
      description: 'Xóa tất cả hóa đơn',
      category: 'invoices',
    },
    {
      resource: 'invoices',
      action: 'complete',
      scope: 'own',
      name: 'invoices.complete.own',
      description: 'Hoàn thành hóa đơn',
      category: 'invoices',
    },
    {
      resource: 'invoices',
      action: 'cancel',
      scope: 'own',
      name: 'invoices.cancel.own',
      description: 'Hủy hóa đơn của mình',
      category: 'invoices',
    },
    {
      resource: 'invoices',
      action: 'cancel',
      scope: 'all',
      name: 'invoices.cancel.all',
      description: 'Hủy tất cả hóa đơn',
      category: 'invoices',
    },
    {
      resource: 'invoices',
      action: 'view',
      scope: 'own',
      field: 'cost',
      name: 'invoices.view.cost',
      description: 'Xem giá vốn hóa đơn',
      category: 'invoices',
    },
    {
      resource: 'invoices',
      action: 'view',
      scope: 'own',
      field: 'profit',
      name: 'invoices.view.profit',
      description: 'Xem lợi nhuận hóa đơn',
      category: 'invoices',
    },
    {
      resource: 'products',
      action: 'view',
      scope: 'all',
      name: 'products.view',
      description: 'Xem sản phẩm',
      category: 'products',
    },
    {
      resource: 'products',
      action: 'create',
      scope: 'all',
      name: 'products.create',
      description: 'Tạo sản phẩm',
      category: 'products',
    },
    {
      resource: 'products',
      action: 'update',
      scope: 'all',
      name: 'products.update',
      description: 'Sửa sản phẩm',
      category: 'products',
    },
    {
      resource: 'products',
      action: 'delete',
      scope: 'all',
      name: 'products.delete',
      description: 'Xóa sản phẩm',
      category: 'products',
    },
    {
      resource: 'products',
      action: 'view',
      scope: 'all',
      field: 'cost',
      name: 'products.view.cost',
      description: 'Xem giá vốn sản phẩm',
      category: 'products',
    },
    {
      resource: 'products',
      action: 'edit',
      scope: 'all',
      field: 'cost',
      name: 'products.edit.cost',
      description: 'Sửa giá vốn sản phẩm',
      category: 'products',
    },
    {
      resource: 'products',
      action: 'view',
      scope: 'all',
      field: 'price',
      name: 'products.view.price',
      description: 'Xem giá bán sản phẩm',
      category: 'products',
    },
    {
      resource: 'products',
      action: 'edit',
      scope: 'all',
      field: 'price',
      name: 'products.edit.price',
      description: 'Sửa giá bán sản phẩm',
      category: 'products',
    },
    {
      resource: 'customers',
      action: 'view',
      scope: 'own',
      name: 'customers.view.own',
      description: 'Xem khách hàng của mình',
      category: 'customers',
    },
    {
      resource: 'customers',
      action: 'view',
      scope: 'branch',
      name: 'customers.view.branch',
      description: 'Xem khách hàng trong chi nhánh',
      category: 'customers',
    },
    {
      resource: 'customers',
      action: 'view',
      scope: 'all',
      name: 'customers.view.all',
      description: 'Xem tất cả khách hàng',
      category: 'customers',
    },
    {
      resource: 'customers',
      action: 'create',
      scope: 'own',
      name: 'customers.create',
      description: 'Tạo khách hàng',
      category: 'customers',
    },
    {
      resource: 'customers',
      action: 'update',
      scope: 'own',
      name: 'customers.update.own',
      description: 'Sửa khách hàng của mình',
      category: 'customers',
    },
    {
      resource: 'customers',
      action: 'update',
      scope: 'all',
      name: 'customers.update.all',
      description: 'Sửa tất cả khách hàng',
      category: 'customers',
    },
    {
      resource: 'customers',
      action: 'delete',
      scope: 'all',
      name: 'customers.delete',
      description: 'Xóa khách hàng',
      category: 'customers',
    },
    {
      resource: 'customers',
      action: 'view',
      scope: 'all',
      field: 'debt',
      name: 'customers.view.debt',
      description: 'Xem công nợ khách hàng',
      category: 'customers',
    },
    {
      resource: 'customers',
      action: 'edit',
      scope: 'all',
      field: 'debt',
      name: 'customers.edit.debt',
      description: 'Sửa công nợ khách hàng',
      category: 'customers',
    },
    {
      resource: 'suppliers',
      action: 'view',
      scope: 'all',
      name: 'suppliers.view',
      description: 'Xem nhà cung cấp',
      category: 'suppliers',
    },
    {
      resource: 'suppliers',
      action: 'create',
      scope: 'all',
      name: 'suppliers.create',
      description: 'Tạo nhà cung cấp',
      category: 'suppliers',
    },
    {
      resource: 'suppliers',
      action: 'update',
      scope: 'all',
      name: 'suppliers.update',
      description: 'Sửa nhà cung cấp',
      category: 'suppliers',
    },
    {
      resource: 'suppliers',
      action: 'delete',
      scope: 'all',
      name: 'suppliers.delete',
      description: 'Xóa nhà cung cấp',
      category: 'suppliers',
    },
    {
      resource: 'cashflows',
      action: 'view',
      scope: 'own',
      name: 'cashflows.view.own',
      description: 'Xem phiếu thu chi của mình',
      category: 'cashflows',
    },
    {
      resource: 'cashflows',
      action: 'view',
      scope: 'branch',
      name: 'cashflows.view.branch',
      description: 'Xem phiếu thu chi chi nhánh',
      category: 'cashflows',
    },
    {
      resource: 'cashflows',
      action: 'view',
      scope: 'all',
      name: 'cashflows.view.all',
      description: 'Xem tất cả phiếu thu chi',
      category: 'cashflows',
    },
    {
      resource: 'cashflows',
      action: 'create',
      scope: 'own',
      name: 'cashflows.create',
      description: 'Tạo phiếu thu chi',
      category: 'cashflows',
    },
    {
      resource: 'cashflows',
      action: 'approve',
      scope: 'branch',
      name: 'cashflows.approve.branch',
      description: 'Duyệt phiếu thu chi chi nhánh',
      category: 'cashflows',
    },
    {
      resource: 'cashflows',
      action: 'approve',
      scope: 'all',
      name: 'cashflows.approve.all',
      description: 'Duyệt tất cả phiếu thu chi',
      category: 'cashflows',
    },
    {
      resource: 'reports',
      action: 'view',
      scope: 'branch',
      name: 'reports.view.branch',
      description: 'Xem báo cáo chi nhánh',
      category: 'reports',
    },
    {
      resource: 'reports',
      action: 'view',
      scope: 'all',
      name: 'reports.view.all',
      description: 'Xem tất cả báo cáo',
      category: 'reports',
    },
    {
      resource: 'reports',
      action: 'export',
      scope: 'branch',
      name: 'reports.export.branch',
      description: 'Xuất báo cáo chi nhánh',
      category: 'reports',
    },
    {
      resource: 'reports',
      action: 'export',
      scope: 'all',
      name: 'reports.export.all',
      description: 'Xuất tất cả báo cáo',
      category: 'reports',
    },
    {
      resource: 'inventory',
      action: 'view',
      scope: 'branch',
      name: 'inventory.view.branch',
      description: 'Xem tồn kho chi nhánh',
      category: 'inventory',
    },
    {
      resource: 'inventory',
      action: 'view',
      scope: 'all',
      name: 'inventory.view.all',
      description: 'Xem tất cả tồn kho',
      category: 'inventory',
    },
    {
      resource: 'inventory',
      action: 'adjust',
      scope: 'branch',
      name: 'inventory.adjust.branch',
      description: 'Điều chỉnh tồn kho chi nhánh',
      category: 'inventory',
    },
    {
      resource: 'inventory',
      action: 'adjust',
      scope: 'all',
      name: 'inventory.adjust.all',
      description: 'Điều chỉnh tất cả tồn kho',
      category: 'inventory',
    },
    {
      resource: 'users',
      action: 'view',
      scope: 'all',
      name: 'users.view',
      description: 'Xem người dùng',
      category: 'admin',
    },
    {
      resource: 'users',
      action: 'create',
      scope: 'all',
      name: 'users.create',
      description: 'Tạo người dùng',
      category: 'admin',
    },
    {
      resource: 'users',
      action: 'update',
      scope: 'all',
      name: 'users.update',
      description: 'Sửa người dùng',
      category: 'admin',
    },
    {
      resource: 'users',
      action: 'delete',
      scope: 'all',
      name: 'users.delete',
      description: 'Xóa người dùng',
      category: 'admin',
    },
    {
      resource: 'roles',
      action: 'view',
      scope: 'all',
      name: 'roles.view',
      description: 'Xem vai trò',
      category: 'admin',
    },
    {
      resource: 'roles',
      action: 'create',
      scope: 'all',
      name: 'roles.create',
      description: 'Tạo vai trò',
      category: 'admin',
    },
    {
      resource: 'roles',
      action: 'update',
      scope: 'all',
      name: 'roles.update',
      description: 'Sửa vai trò',
      category: 'admin',
    },
    {
      resource: 'roles',
      action: 'delete',
      scope: 'all',
      name: 'roles.delete',
      description: 'Xóa vai trò',
      category: 'admin',
    },
    {
      resource: 'permissions',
      action: 'view',
      scope: 'all',
      name: 'permissions.view',
      description: 'Xem quyền',
      category: 'admin',
    },
    {
      resource: 'permissions',
      action: 'assign',
      scope: 'all',
      name: 'permissions.assign',
      description: 'Gán quyền',
      category: 'admin',
    },
    {
      resource: 'branches',
      action: 'view',
      scope: 'all',
      name: 'branches.view',
      description: 'Xem chi nhánh',
      category: 'admin',
    },
    {
      resource: 'branches',
      action: 'create',
      scope: 'all',
      name: 'branches.create',
      description: 'Tạo chi nhánh',
      category: 'admin',
    },
    {
      resource: 'branches',
      action: 'update',
      scope: 'all',
      name: 'branches.update',
      description: 'Sửa chi nhánh',
      category: 'admin',
    },
    {
      resource: 'branches',
      action: 'delete',
      scope: 'all',
      name: 'branches.delete',
      description: 'Xóa chi nhánh',
      category: 'admin',
    },
    {
      resource: 'audit-logs',
      action: 'view',
      scope: 'all',
      name: 'audit-logs.view',
      description: 'Xem lịch sử thao tác',
      category: 'admin',
    },
    {
      resource: 'print-templates',
      action: 'view',
      scope: 'all',
      name: 'print-templates.view',
      description: 'Xem mẫu in',
      category: 'admin',
    },
    {
      resource: 'print-templates',
      action: 'create',
      scope: 'all',
      name: 'print-templates.create',
      description: 'Tạo mẫu in',
      category: 'admin',
    },
    {
      resource: 'print-templates',
      action: 'update',
      scope: 'all',
      name: 'print-templates.update',
      description: 'Sửa mẫu in',
      category: 'admin',
    },
    {
      resource: 'print-templates',
      action: 'delete',
      scope: 'all',
      name: 'print-templates.delete',
      description: 'Xóa mẫu in',
      category: 'admin',
    },
    {
      resource: 'settings',
      action: 'view',
      scope: 'all',
      name: 'settings.view',
      description: 'Xem cài đặt',
      category: 'admin',
    },
    {
      resource: 'settings',
      action: 'update',
      scope: 'all',
      name: 'settings.update',
      description: 'Sửa cài đặt',
      category: 'admin',
    },
  ];

  for (const perm of permissions) {
    await prisma.permission.upsert({
      where: { name: perm.name },
      update: {},
      create: perm,
    });
  }

  const fieldPermissions = [
    { resource: 'orders', fieldName: 'discount', fieldLabel: 'Giảm giá' },
    { resource: 'orders', fieldName: 'cost', fieldLabel: 'Giá vốn' },
    { resource: 'orders', fieldName: 'profit', fieldLabel: 'Lợi nhuận' },
    { resource: 'orders', fieldName: 'description', fieldLabel: 'Ghi chú' },
    { resource: 'invoices', fieldName: 'discount', fieldLabel: 'Giảm giá' },
    { resource: 'invoices', fieldName: 'cost', fieldLabel: 'Giá vốn' },
    { resource: 'invoices', fieldName: 'profit', fieldLabel: 'Lợi nhuận' },
    { resource: 'products', fieldName: 'cost', fieldLabel: 'Giá vốn' },
    { resource: 'products', fieldName: 'price', fieldLabel: 'Giá bán' },
    { resource: 'customers', fieldName: 'debt', fieldLabel: 'Công nợ' },
  ];

  for (const fp of fieldPermissions) {
    await prisma.fieldPermission.upsert({
      where: {
        resource_fieldName: {
          resource: fp.resource,
          fieldName: fp.fieldName,
        },
      },
      update: {},
      create: fp,
    });
  }

  const columnPermissions = [
    { resource: 'orders', columnName: 'code', columnLabel: 'Mã đơn', order: 1 },
    {
      resource: 'orders',
      columnName: 'customer',
      columnLabel: 'Khách hàng',
      order: 2,
    },
    {
      resource: 'orders',
      columnName: 'total',
      columnLabel: 'Tổng tiền',
      order: 3,
    },
    {
      resource: 'orders',
      columnName: 'discount',
      columnLabel: 'Giảm giá',
      order: 4,
    },
    {
      resource: 'orders',
      columnName: 'cost',
      columnLabel: 'Giá vốn',
      order: 5,
    },
    {
      resource: 'orders',
      columnName: 'profit',
      columnLabel: 'Lợi nhuận',
      order: 6,
    },
    {
      resource: 'orders',
      columnName: 'status',
      columnLabel: 'Trạng thái',
      order: 7,
    },
    {
      resource: 'orders',
      columnName: 'createdAt',
      columnLabel: 'Ngày tạo',
      order: 8,
    },
  ];

  for (const cp of columnPermissions) {
    await prisma.columnPermission.upsert({
      where: {
        resource_columnName: {
          resource: cp.resource,
          columnName: cp.columnName,
        },
      },
      update: {},
      create: cp,
    });
  }
}

seedPermissions()
  .then(() => console.log('Permissions seeded'))
  .catch((e) => console.error(e))
  .finally(() => prisma.$disconnect());
