export const INTERNAL_FINANCE_DIRECTION = {
  EXPENSE: 'EXPENSE',
  RECEIPT: 'RECEIPT',
} as const;

export const INTERNAL_FINANCE_CATEGORY = {
  DELIVERY_FEE: 'DELIVERY_FEE',
  FUEL: 'FUEL',
  VEHICLE_CARE: 'VEHICLE_CARE',
  SALARY_ADVANCE: 'SALARY_ADVANCE',
  CUSTOMER_RECEIPT: 'CUSTOMER_RECEIPT',
  MANUAL_RECEIPT: 'MANUAL_RECEIPT',
  OTHER_EXPENSE: 'OTHER_EXPENSE',
} as const;

export const INTERNAL_FINANCE_SUBCATEGORY = {
  FEE_GUI_BEN: 'FEE_GUI_BEN',
  FEE_GRAB: 'FEE_GRAB',
  SHIPPING_OUT: 'SHIPPING_OUT',
  SHIPPING_IN: 'SHIPPING_IN',
  FUEL: 'FUEL',
  VEHICLE_CARE: 'VEHICLE_CARE',
  SALARY_ADVANCE: 'SALARY_ADVANCE',
  OTHER: 'OTHER',
  WAREHOUSE_ITEM_SALE: 'WAREHOUSE_ITEM_SALE',
} as const;

export const INTERNAL_FINANCE_BRANCH_CODES: Record<number, string> = {
  6: 'HN',
  1: 'SG',
  4: 'VPHN',
  7: 'VPSG',
};

export const INTERNAL_FINANCE_STATUS = {
  PENDING_ACCOUNTANT: 'PENDING_ACCOUNTANT',
  ACCOUNTANT_APPROVED: 'ACCOUNTANT_APPROVED',
  PENDING_MANAGER: 'PENDING_MANAGER',
  MANAGER_APPROVED: 'MANAGER_APPROVED',
  READY_FOR_WEEKLY_APPROVAL: 'READY_FOR_WEEKLY_APPROVAL',
  IN_WEEKLY_APPROVAL: 'IN_WEEKLY_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  POSTING: 'POSTING',
  POSTED: 'POSTED',
  CANCELLED: 'CANCELLED',
} as const;

export const INTERNAL_FINANCE_EVIDENCE_STATUS = {
  COMPLETE: 'COMPLETE',
  MISSING: 'MISSING',
  EXCEPTION_APPROVED: 'EXCEPTION_APPROVED',
} as const;

export const INTERNAL_FINANCE_REVIEW_ROLE = {
  ACCOUNTANT: 'ACCOUNTANT',
  MANAGER: 'MANAGER',
} as const;

export const INTERNAL_FINANCE_REVIEW_DECISION = {
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  MARK_MISSING: 'MARK_MISSING',
  EXCEPTION_APPROVE: 'EXCEPTION_APPROVE',
} as const;

export const INTERNAL_FINANCE_WEEKLY_STATUS = {
  DRAFT: 'DRAFT',
  READY: 'READY',
  IN_APPROVAL: 'IN_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  POSTED: 'POSTED',
} as const;

export const INTERNAL_FINANCE_BRANCH_IDS = [1, 4, 6, 7] as const;

export const WAREHOUSE_CASH_BRANCH_IDS = [6, 1] as const;

export const DELIVERY_EXPENSE_CATEGORIES = [
  INTERNAL_FINANCE_CATEGORY.DELIVERY_FEE,
] as const;

export const POSTABLE_INTERNAL_FINANCE_STATUSES = new Set([
  INTERNAL_FINANCE_STATUS.ACCOUNTANT_APPROVED,
  INTERNAL_FINANCE_STATUS.MANAGER_APPROVED,
  INTERNAL_FINANCE_STATUS.APPROVED,
]);
